name: 'Setup Android Project'
description: 'Decodes google-services.json and sets up Java and Gradle'

runs:
  using: "composite"
  steps:
    - name: Decode google-services.json
      shell: bash
      run: echo "${GOOGLE_SERVICES_JSON}" | base64 --decode > app/google-services.json

    - name: Setup JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5