name: 'Setup Android Project'
description: 'Decodes google-services.json and sets up Java and Gradle'
inputs:
  google-services-json:
    description: 'Base64 encoded google-services.json'
    required: true

runs:
  using: "composite"
  steps:
    - name: Decode google-services.json
      shell: bash
      run: echo "${{ inputs.google-services-json }}" | base64 --decode > app/google-services.json

    - name: Setup JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
